name: Sigstore experiment

on: push
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  example:
    runs-on: ubuntu-latest

    permissions: {}

    name: Install Cosign
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Check install!
        run: cosign version